package graph;

public class CreateGraph1 {
	// CREATING GRAPH THROUGH ADJACENCY MATRIX
	
	// CREATING V*V MATRIX 
	// AND STORE ONLY 0(FOR WHICH NO LINK BETWEEN FROM I TO J) OR 1(FOR WHICH A LINK BETWWEN FROM I TO J)
	/// SPACE  O(V^2)  AND FOR FINDING NEIGHBOUR   O(V)
	// FOR WEIGHTED GRAPH , FOR NO LINK BETWEEN NODES STORE 0, AND FOR VALUE 1- STORE DIRECTLY WEIGHT
	

	
	/// GRAPH CREATING THROUGH IMPLICIT GRAPH(2-D ARRAY)
	
	// FOR ANY (I,J) INDEX , 4 NEIGHBOURS
	/// UP, (I-1,J)     DOWN(I+1,J)
	// LEFT  (I,J-1)     RIGHT(I,J+1)
	
	public static void main(String[] args) {
		// TODO Auto-generated method stub

	}

}
